### PR TITLE
add connection config when connect to zk

### PR DESCRIPTION
**Pull request by cyflhn**
add connection config when connect to zk

### CODE REVIEW

**Comment by cyflhn** [comment]
什么原因导致持续集成失败 ，我点击detail看不到任何内容啊

**Comment by ngaut** [comment]
https://travis-ci.org/ngaut/go-zookeeper/builds/72934058

**Comment by cyflhn** [comment]
只能看见 Do you have a question? 页面js报错

**Comment by cyflhn** [comment]
能截个图给我看下吗  我看不到页面内容

**Comment by ngaut** [comment]
Could you using chrome to view the page ?

**Comment by cyflhn** [comment]
我看见几个用例都pass了哇，只有The command "go get code.google.com/p/go.tools/cmd/vet" exited with 2. 是不是这个原因导致的

**Comment by cyflhn** [comment]
https://travis-ci.org/ngaut/go-zookeeper/builds/72941404
 would you please explain the test result ? I do not know what checks have failed.

**Comment by cyflhn** [comment]
能从持续集成中把vet移除吗，这一步总是报错唉

**Pull request closed without merging**
